<section id="page-title" class="page-title-parallax page-title-center page-title-dark include-header" style="background-image: linear-gradient(to top, rgba(254,150,3,0.5), #39384D), url('/demos/seo/images/faqs-title.jpg'); background-size: cover; padding: 120px 0;" data-bottom-top="background-position:0px 300px;" data-top-bottom="background-position:0px -300px;">
    <div id="particles-line"></div>

    <div class="container clearfix mt-4">
        <div class="badge rounded-pill border border-light text-light">Kullanıcı Bilgilendirme</div>
        <h1>KİŞİSEL VERİLERİN KORUNMASI KANUNU
            KAPSAMINDA AYDINLATMA METNİ</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Ana Sayfa</a></li>
            <li class="breadcrumb-item active" aria-current="page">Destek</li>
        </ol>
    </div>
</section>
<section id="content">

    <div class="content-wrap pt-0">

        <!-- Features
            ============================================= -->
        <div class="section bg-transparent mt-4 mb-0 pb-0">
            <div class="container">
            <p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;'><strong><u>KİŞİSEL VERİLERİN KORUNMASI KANUNU KAPSAMINDA</u></strong><br><strong><u>M&Uuml;ŞTERİ AYDINLATMA METNİ</u></strong></p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;'><strong>&nbsp;</strong></p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong>JUNOMONEY ELEKTRONİK PARA VE &Ouml;DEME HİZMETLERİ A.Ş. &nbsp;</strong>(&ldquo;Şirket&rdquo;) olarak; veri sorumlusu sıfatıyla, kişisel verilerinizin g&uuml;venliği hususuna verdiğimiz &ouml;nem doğrultusunda b&uuml;nyemizde barındırdığımız her t&uuml;rl&uuml; kişisel veri 6698 sayılı Kişisel Verilerin Korunması Kanunu(&ldquo;KVKK&rdquo;)&rsquo;na uygun olarak işlenmekte, saklanmakta ve aktarılmaktadır.&nbsp;</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>&nbsp;</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>İşbu aydınlatma metni veri sorumlusu sıfatıyla Şirket tarafından toplanan, saklanan ve işlenen kişisel verilerinize ilişkin olarak KVKK&rsquo;nun &ldquo;Veri Sorumlusunun Aydınlatma Y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;&rdquo; başlıklı 10. Maddesi ile Aydınlatma Y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;n&uuml;n Yerine Getirilmesinde Uyulacak Usul Ve Esaslar Hakkında Tebliğ uyarınca hazırlanmıştır.&nbsp;</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><u><span style="text-decoration:none;">&nbsp;</span></u></strong></p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><u>KİŞİSEL VERİLERİNİZİN İŞLENME AMA&Ccedil;LARI</u></strong></p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Kişisel verileriniz aşağıda yer alan sınırlı ama&ccedil;lar doğrultusunda işlenmektedir:<br>&nbsp;Şirket tarafından kişisel verileriniz;</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>&nbsp;</p>
<ul style="list-style-type: undefined;margin-left:0in;">
    <li>Başta finansal g&uuml;venlik s&uuml;re&ccedil;lerinin (KYC(M&uuml;şterini Tanı), AML (Karaparanın Aklanmasının &Ouml;nlenmesi), anti-fraud(Dolandırıcılığın &Ouml;nlenmesi) ve diğer us&uuml;ls&uuml;z işlemlerle m&uuml;cadele gibi) y&ouml;netimi,&nbsp;</li>
    <li>Şirket hizmetlerinden siz m&uuml;şterilerimizin yararlanabilmesinin sağlanması,&nbsp;</li>
    <li>Şirket&rsquo;in ticari faaliyetlerini s&uuml;rd&uuml;rebilmesi i&ccedil;in gerekli faaliyetlerin y&uuml;r&uuml;t&uuml;lmesi ile 6493 s. &Ouml;DEME VE MENKUL KIYMET MUTABAKAT SİSTEMLERİ, &Ouml;DEME HİZMETLERİ VE ELEKTRONİK PARA KURULUŞLARI HAKKINDA KANUN ve alt d&uuml;zenlemeleri gereğince &ouml;deme hizmetleri faaliyetleri ile ilişkili olarak ve 6698 sayılı Kanun&rsquo;un 5. ve 6. maddelerinde belirtilen kişisel veri işleme şartları ile Şirketimiz tarafından y&uuml;r&uuml;t&uuml;len ticari ve insan kaynakları alanında faaliyetlerin ger&ccedil;ekleştirilmesi i&ccedil;in ilgili iş birimlerimiz tarafından gerekli &ccedil;alışmaların yapılması ve buna bağlı iş s&uuml;re&ccedil;lerinin y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>İş ortakları ve tedarik&ccedil;ilerin bilgiye erişim yetkilerinin planlanması ve icrası,&nbsp;</li>
    <li>Finans ve muhasebe işlerinin takibi,&nbsp;</li>
    <li>Satın alma s&uuml;re&ccedil;lerinin planlanması ve icrası,&nbsp;</li>
    <li>Kurumsal iletişim ve y&ouml;netim faaliyetlerinin planlanması ve icrası,&nbsp;</li>
    <li>Bilgi g&uuml;venliği s&uuml;re&ccedil;lerinin planlanması denetimi ve icrası,&nbsp;</li>
    <li>S&ouml;zleşme s&uuml;re&ccedil;lerinin ve hukuki taleplerin takibi,&nbsp;</li>
    <li>İş &nbsp;ortakları ve tedarik&ccedil;ilerle olan ilişkilerin y&ouml;netimi &nbsp;ve icrası ,&nbsp;</li>
    <li>Satış sonrası destek hizmetleri aktivitelerinin planlanması ve icrası,&nbsp;</li>
    <li>M&uuml;şteri talep ve şikayetlerinin takibi, M&uuml;şteri ilişkileri y&ouml;netimi,</li>
    <li>Etkinlik y&ouml;netimi,Satın alma s&uuml;re&ccedil;lerinin planlanması ve icrası,&nbsp;</li>
    <li>Mal / Hizmet Satın Alım S&uuml;re&ccedil;lerinin Y&uuml;r&uuml;t&uuml;lmesi, Mal / Hizmet Satış Sonrası Destek Hizmetlerinin Y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>Mal / Hizmet Satış S&uuml;re&ccedil;lerinin Y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>Mal / Hizmet &Uuml;retim Ve Operasyon S&uuml;re&ccedil;lerinin Y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>M&uuml;şteri İlişkileri Y&ouml;netimi S&uuml;re&ccedil;lerinin Y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>&Uuml;retim ve operasyon s&uuml;re&ccedil;lerinin planlanması ve icrası,&nbsp;</li>
    <li>Eğitim Faaliyetlerinin Y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>Fiziksel Mekan G&uuml;venliğinin Temini,&nbsp;</li>
    <li>Hukuk İşlerinin Takibi Ve Y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>Yetkili Kişi, Kurum Ve Kuruluşlara Bilgi Verilmesi,&nbsp;</li>
    <li>Y&ouml;netim Faaliyetlerinin Y&uuml;r&uuml;t&uuml;lmesi,</li>
    <li>Faaliyetlerin Mevzuata Uygun Y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>Veri Sorumlusu Operasyonlarının G&uuml;venliğinin Temini,&nbsp;</li>
    <li>Ticari faaliyetin s&uuml;rd&uuml;r&uuml;lmesi, Denetim / Etik Faaliyetlerinin Y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>İ&ccedil; Denetim/ Soruşturma / İstihbarat Faaliyetlerinin y&uuml;r&uuml;t&uuml;lmesi,&nbsp;</li>
    <li>Taşınır Mal Ve Kaynakların G&uuml;venliğinin Temini.<br>&nbsp;<br>&nbsp;</li>
</ul>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><u>KİŞİSEL VERİLERİNİZİN 3. KİŞİLERE AKTARILMASI VE AMACI</u></strong></p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Şirket, Kanunun 6. maddesinde yer alan &Ouml;zel Nitelikli Kişisel verilerin işlenmesine ilişkin ve 8. ve 9. maddeler de yer alan kişisel verilerin aktarılması konusunda &ouml;ng&ouml;r&uuml;len d&uuml;zenlemelere ve Kişisel Verileri Koruma Kurumu tarafından yayımlanan esaslara uygun davranmaktadır.</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;'>Kanun 5. madde kapsamında, aşağıda belirtilen durumlarda Şirket ilgili kişilerin verilerini a&ccedil;ık rıza almaksızın aktarılabilmektedir;<br>&nbsp;a) Kanunlarda a&ccedil;ık&ccedil;a &ouml;ng&ouml;r&uuml;lmesi.<br>&nbsp;b) Fiili imk&acirc;nsızlık nedeniyle rızasını a&ccedil;ıklayamayacak durumda bulunan veya rızasına hukuki ge&ccedil;erlilik tanınmayan kişinin kendisinin ya da bir başkasının hayatı veya beden b&uuml;t&uuml;nl&uuml;ğ&uuml;n&uuml;n korunması i&ccedil;in zorunlu olması.<br>&nbsp;c) Bir s&ouml;zleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla, s&ouml;zleşmenin taraflarına ait kişisel verilerin işlenmesinin gerekli olması.<br>&nbsp;&ccedil;) Veri sorumlusunun hukuki y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;n&uuml; yerine getirebilmesi i&ccedil;in zorunlu olması.<br>&nbsp;d) İlgili kişinin kendisi tarafından alenileştirilmiş olması.<br>&nbsp;e) Bir hakkın tesisi, kullanılması veya korunması i&ccedil;in veri işlemenin zorunlu olması.<br>&nbsp;f) İlgili kişinin temel hak ve &ouml;zg&uuml;rl&uuml;klerine zarar vermemek kaydıyla, veri sorumlusunun meşru menfaatleri i&ccedil;in veri işlenmesinin zorunlu olması.</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>&nbsp;</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Kişisel verileriniz, Kanun ve sair mevzuat kapsamında ve yukarıda yer verilen sınırlı ama&ccedil;larla BDDK, MASAK, T.C. Merkez Bankası gibi hukuken yetkili kamu kurumu veya &ouml;zel kurum/kuruluşlarla, Şirket&rsquo;in yurti&ccedil;i ve yurtdışındaki doğrudan veya dolaylı iştirakleri ve ana ortaklarıyla, Şirket&rsquo;in dış hizmeti sağlayıcıları, iş ortakları, danışmanları ve tedarik&ccedil;ileriyle, Şirket&rsquo;in temsilcilik sıfatı ile faaliyetlerini y&uuml;r&uuml;tmek &uuml;zere temsilcileri ile MasterCard ve Visa gibi yabancı/uluslararası kamu kuruluşlarıyla veya &ouml;zel kurum ve kuruluşlarla, kanunen yetkili kılınmış kamu t&uuml;zel kişilikleri, &ouml;zel kişiler veya adli makamlarla, Emniyet Genel M&uuml;d&uuml;rl&uuml;ğ&uuml; ve sair kolluk kuvvetleri, N&uuml;fus Genel M&uuml;d&uuml;rl&uuml;ğ&uuml;, her t&uuml;rl&uuml; yargı makamı, yetki vermiş olduğunuz temsilcileriniz, avukatlar, vergi ve finans danışmanları da d&acirc;hil olmak &uuml;zere danışmanlık aldığımız &uuml;&ccedil;&uuml;nc&uuml; kişiler, d&uuml;zenleyici ve denetleyici kurumlar, resmi merciler d&acirc;hil yukarıda belirtilen ama&ccedil;larla geliştirmek veya y&uuml;r&uuml;tmek &uuml;zere işbirliği yaptığımız iş ortaklarımız ve bu kapsamda gereken hukuki altyapı oluştuğunda yurt dışına aktarılabilecektir.&nbsp;</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>&nbsp;</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Kişisel verileriniz ticaret sitemize hizmet veren kuruluşlara, grup şirketlerine, s&ouml;zleşmeye dayalı iş ilişkisinde olduğu danışman ve m&uuml;şavirlerine, hizmet tedarik&ccedil;ilerine,&nbsp;faaliyetin getirdiği yasal zorunluluklar kapsamında kamu kuruluşları ve mevzuatla tanımlanmış diğer kuruluşlara aktarabilmektedir.</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>&nbsp;</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><u>KİŞİSEL VERİLERİNİZİN TOPLANMA Y&Ouml;NTEMİ VE HUKUKİ SEBEBİ</u></strong></p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Kişisel veriler ; Şirketin meşru menfaati gereği sizden bizzat talep ettiğimiz, ticaret sitemize hizmet veren kuruluşlara yaptığınız başvurularla, web sitelerimiz &uuml;zerinden yapılmış olan dijital başvurular, santralimiz, dilek&ccedil;eleriniz, hukuki tebligatlar, hukuki s&uuml;re&ccedil;te gereken belgeler ve tutanaklar, denetim esnasında yapılan kayıtlar, KVKK Mad.11 kapsamında şirketimize yapılan başvuru bilgileri vasıtasıyla toplanmakta olup yasal s&uuml;reler ve işin gerektirdiği şartlar kapsamında saklanmaktadır.</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Kişisel verileriniz, Kişisel Verilerin Korunması Kanunu Mad. 5/2-c : &ldquo; Bir s&ouml;zleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla, s&ouml;zleşmenin taraflarına ait ait kişisel verilerin işlenmesinin gerekli olması&rdquo;,Kişisel Verilerin Korunması Kanunu Mad. 5/2-&ccedil;: &ldquo;Veri sorumlusunun hukuki y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;n&uuml; yerine getirebilmesi i&ccedil;in zorunlu olması&rdquo;,Kişisel Verilerin Korunması Kanunu Mad. 5/2-e: &ldquo; Bir hakkın tesisi, kullanılması veya korunması i&ccedil;in veri işlemenin zorunlu olması&rdquo;ve Sosyal G&uuml;venlik Kurumuna ve 4857 Sayılı İş Kanuna karşı y&uuml;k&uuml;ml&uuml;l&uuml;klerin yerine getirilmesi hukuki sebeplerine dayanarak işlenmektedir.</p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><u><span style="text-decoration:none;">&nbsp;</span></u></strong></p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><u>HAKLARINIZ</u></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:normal;background:white;'><span style='font-family:"Times New Roman",serif;color:#212529;'>- Kişisel verilerinizin işlenip işlenmediğini &ouml;ğrenme,<br>&nbsp;- Kişisel verileriniz işlenmişse buna ilişkin bilgi talep etme,<br>&nbsp;- Kişisel verilerinizin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını &ouml;ğrenme,<br>&nbsp;- Yurt i&ccedil;inde veya yurt dışında kişisel verilerinizin aktarıldığı &uuml;&ccedil;&uuml;nc&uuml; kişileri bilme,<br>&nbsp;- Kişisel verilerinizin eksik veya yanlış işlenmiş olması halinde bunların d&uuml;zeltilmesini isteme ve bu kapsamda yapılan işlemin kişisel verilerin aktarıldığı &uuml;&ccedil;&uuml;nc&uuml; kişilere bildirilmesini isteme,<br>&nbsp;- KVKK ve ilgili diğer kanun h&uuml;k&uuml;mlerine uygun olarak işlenmiş olmasına rağmen, işlenmesini gerektiren sebeplerin ortadan kalkmış olması halinde kişisel verilerinizin silinmesini, yok edilmesi veya anonim hale getirilmesini isteme, bu kapsamda yapılan işlemin kişisel verilerinizin aktarıldığı &uuml;&ccedil;&uuml;nc&uuml; kişilere bildirilmesini isteme,<br>&nbsp;- İşlenen verilerinizin m&uuml;nhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle aleyhinize bir sonucun ortaya &ccedil;ıkmasına itiraz etme,<br>&nbsp;- Kişisel verilerinizin kanuna aykırı olarak işlenmesi sebebiyle zarara uğramanız halinde zararın giderilmesini talep etme.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:normal;background:white;'><span style='font-family:"Times New Roman",serif;color:#212529;'>İlgili Kişi olarak yukarıda bahsi ge&ccedil;en haklarınıza ilişkin taleplerinizi;</span></p>
<ul style="margin-bottom:0in;margin-top:0in;" type="disc">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;color:#212529;line-height:normal;background:white;'><span style='font-family:"Times New Roman",serif;'>&ldquo; www.junomoney.com.tr<strong><em>&rdquo;&nbsp;</em></strong> e-posta adresimizde yer alan <strong>&lsquo;</strong></span><span style="color:black;"><a href="https://junomoney.com.tr/support/documents/kisisel-bilgi-basvuru"><strong><span style='font-family:"Times New Roman",serif;'>&rsquo;Kişisel Veri Sahibi Başvuru Formu</span></strong></a></span><strong><span style='font-family:"Times New Roman",serif;'>&rsquo;&rsquo;nu</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp;doldurarak kimliğinizi tespit edici gerekli bilgiler ile birlikte kisiselveri@junomoney.com.tr e-posta adresine g&uuml;venli elektronik imza veya mobil imza ile imzalayarak g&ouml;nderebilir yahut</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;color:#212529;line-height:normal;background:white;'><span style='font-family:"Times New Roman",serif;'>İş bu formun ıslak imzalı kopyasını bizzat elden veya noter aracılığıyla yahut iadeli taahh&uuml;tl&uuml; mektupla &quot; Barbaros Mah. Begonya Sok. No:7/17 A+Live Tower Ataşehir-İSTANBUL &quot; adresimize veya</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;color:#212529;line-height:normal;background:white;'><span style='font-family:"Times New Roman",serif;'>Kayıtlı Elektronik Posta (KEP) hesabımız&nbsp;</span><span style="color:black;"><a href="mailto:junomoney@hs01.kep.tr"><span style='font-family:"Times New Roman",serif;'>junomoney@hs01.kep.tr</span></a></span><span style='font-family:"Times New Roman",serif;'>&nbsp;adresine KEP &uuml;zerinden g&ouml;nderebilirsiniz.</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:normal;background:white;'><span style='font-family:"Times New Roman",serif;color:#212529;'>Kişisel veri sahibi adına &uuml;&ccedil;&uuml;nc&uuml; bir kişi tarafından talepte bulunulması durumunda ayrıca, başvuruda bulunacak kişi adına noter aracılığıyla d&uuml;zenlenmiş vekaletnameyi ibraz etmeniz gerekmektedir.<br>&nbsp;Şirket, talebinizin niteliğine g&ouml;re Kanun&apos;da &ouml;ng&ouml;r&uuml;ld&uuml;ğ&uuml; &uuml;zere en ge&ccedil; otuz g&uuml;n i&ccedil;erisinde tarafınıza &uuml;cretsiz olarak yazılı cevap vermek suretiyle başvurunuzu sonu&ccedil;landırmayı beyan ve taahh&uuml;t etmektedir. Ancak işlemin ayrıca bir maliyet gerektirmesi halinde Şirket&apos;in Kurulca belirlenen tarifedeki &uuml;creti talep etme hakkı saklıdır.<br>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:normal;background:white;'><span style='font-family:"Times New Roman",serif;color:#212529;'>Kişisel veri sahibinin Kanun&apos;un 14. maddesi gereğince başvurusunun reddedilmesi, verilen cevabı yetersiz bulması veya başvurusuna s&uuml;resinde cevap verilmemesi hallerinde; cevabı &ouml;ğrendiği tarihten itibaren otuz ve her halde başvuru tarihinden itibaren altmış g&uuml;n i&ccedil;inde Kurul&apos;a şikayette bulunma hakkı mevcuttur.</span></p>
<p style='margin:0in;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-family:"Times New Roman",serif;color:#212529;'><br>&nbsp;</span></p>
            </div>
        </div>
    </div>
</section>